codehub2/codehub/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^CodeHub/', include('hub.urls', namespace="CodeHub")),
]


codehub2/hub/urls.py
from django.conf.urls import url

from . import views
app_name = 'hub'
urlpatterns = [
    url(r'^index', views.index, name='index'),
    url(r'^mainPage', views.mainPage),
    url(r'^login', views.login, name='login'),
    url(r'^register', views.register, name='register'),
    url(r'^profile', views.profile,name='profile'),

    url(r'^projectCreate', views.project_create, name='project_create'),
    url(r'^upload', views.upload,name='upload'),
    url(r'^code_file', views.code_file,name='code_file'),
    url(r'^code_edit', views.code_edit,name='code_edit'),
    url(r'^process_edit', views.process_edit,name='process_edit'),
    url(r'^code_new', views.code_new,name='code_new'),
    url(r'^process_new', views.process_new,name='process_new'),
    url(r'^code', views.code, name='code'),
    url(r'^getZip', views.getZip, name='getZip'),


    url(r'^commit', views.commit, name='commit'),

    url(r'^branch', views.branch,name='branch'),
    # url(r'^create_new_branch', views.create_branch, name='newbranch'),
    # url(r'^delete', views.delete_branch, name='deletebranch'),
    # url(r'^merge', views.merge_branch, name='mergebranch'),
    # url(r'^switch', views.switch_branch, name='switchbranch'),
    # url(r'^code_switch', views.code_switch_branch, name='code_switchbranch'),
    # url(r'^create_new_branch', views.branch, name='newbranch'),
    # url(r'^delete', views.branch, name='deletebranch'),
    # url(r'^merge', views.branch, name='mergebranch'),
    # url(r'^switch', views.branch, name='switchbranch'),
    url(r'^code_switch', views.code_switch_branch, name='code_switchbranch'),

    url(r'^member', views.member,name='proMem'),
    url(r'^member', views.member,name='member'),
    url(r'^delMem', views.delMem, name='delMem'),
    
    url(r'^settings', views.settings,name='settings'),
    url(r'^delProject', views.delProject, name='delProject'),
    url(r'^user_record', views.user_record),
    url(r'^projectCatalog', views.profile),
    #url(r'^[\S]+/[\S]+/member', views.member,name='proMem'),
    #url(r'^(?P<project_owner>[\S]+)/(?P<project_name>[\S]+)/member', views.member,name='proMem'),
    #url(r'^member', views.proMem,name='proMem'),
    #url(r'^(?P<project_owner>[\S]+)/(?P<project_name>[\S]+)/$', views.code),
    #url(r'^(?P<project_ii>[0-9]+)/$', views.code),
    #url(r'^edit/action/', views.edit_action, name = 'edit_action'),
]

codehub2/hub/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.shortcuts import get_object_or_404

# Create your models here.
class User(models.Model):
	"""docstring for User"""
	user_name = models.CharField(primary_key=True,max_length=30)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=30)
	def __str__(self):
		return self.user_name
	# def __init__(self, arg):
	# 	super(User, self).__init__()
	# 	self.arg = arg
	# def __str__(self) :
 #        return self.user_id
class  Project(models.Model):
	"""docstring for  Project"""
	# def __init__(self, arg):
	# 	super( Project, self).__init__()
	# 	self.arg = arg
	project_id = models.AutoField(primary_key=True)
	project_name = models.CharField(max_length=100)
	repo_path = models.CharField(max_length=100)
	description = models.CharField(max_length=200)
	lead_user = models.ForeignKey(User)
	def __str__(self):
		return self.project_name

class project_user(models.Model):
	"""docstring for Project_user"""
	project_id = models.IntegerField()
	user_name = models.ForeignKey(User)
	#def __str__(self):
	#	return self.project_id
	#def __str__(self):
	#	return self.project_id,self.user_name
	#def __init__(self, arg):
	# 	super(Project_user, self).__init__()
	# 	self.arg = arg

import time
class user_commit(models.Model):
	commit_id = models.AutoField(primary_key=True)
	user_name = models.ForeignKey(User)
	description = models.CharField(max_length=200)
	commit_time = models.DateTimeField()
	@staticmethod
	def record(usr_name, msg):
		tt = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())
		user_commit.objects.create(user_name = get_object_or_404(User, pk=usr_name),description = msg,commit_time = tt)


codehub2/hub/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect, Http404,HttpResponse
from django.shortcuts import render, render_to_response
from . import models
from django.urls import reverse
from .models import User, project_user, Project
from django.shortcuts import get_object_or_404, render
import pygit2
import json
from models import user_commit
import time
import sys

reload(sys)
sys.setdefaultencoding('utf8')  

from . import GitFileController
import os.path

#服务器仓库地址，所有用户所在的目录
codehub_path = os.path.dirname(__file__)+'/repo/'


# Create your views here.
def index(request):
    return render(request,'index.html')

def mainPage(request):
    return render(request,'mainPage.html')


def code_test(request):
    return render(request,'code.html')


def code(request):
    print '进入代码界面'

    p_owner,p_name = request.GET.get('project_owner'),request.GET.get('project_name')
    if p_owner == None:
        p_owner,p_name = request.session['now_project_owner'],request.session['now_project_name']
    print p_owner,p_name
    project = Project.objects.get(project_name=p_name,lead_user=p_owner)
    #project = Project.objects.get(project_id=res)
    request.session['now_project_id'] = project.project_id
    request.session['now_project_name'] = project.project_name
    request.session['now_project_owner'] = project.lead_user.user_name
    request.session['now_project_repo_path'] = codehub_path + project.lead_user.user_name + '/'+project.project_name+'/'

    #is_leader才能有设置界面，删除项目
    if request.session['now_project_owner'] == request.session['user_name']:
        request.session['is_leader'] = True
    else: request.session['is_leader'] = False

    files = os.listdir(request.session['now_project_repo_path'])
    print (files)
    
    head_branch = GitFileController.get_head_branch(request.session['now_project_repo_path']).split('/')[-1]
    request.session['head_branch']=head_branch
    print (codehub_path + project.repo_path)
    data = GitFileController.show_branches_refs(request.session['now_project_repo_path'])
    return render(request, 'code.html', {'project': project,'files': files,'data':data})




def code_switch_branch(request):
    print '切换分支'
    tobranch = request.POST.get('tobranch')
    GitFileController.switch_branch(request.session['now_project_repo_path'], tobranch)
    request.session['head_branch']=tobranch
    return HttpResponseRedirect(reverse('hub:code'))

def getZip(request):
    print '压缩中'
    GitFileController.zip_dir(request.session['now_project_repo_path'], 'hub/static/my-archive.zip')
    return HttpResponse('my-archive.zip')




def code_edit(request):
    print '代码修改界面'
    file_name = request.session['now_file_name']
    with open(request.session['now_project_repo_path']+file_name,'r') as f:
        data = f.read()
    return render(request,'code_edit.html', {'data': data,'title': file_name})

def code_file(request, *args, **kwargs):
    #print args
    #file_name = (kwargs['file_name'])
    file_name = request.GET.get('file_name')
    if file_name == None: file_name = request.session['now_file_name']
    else: request.session['now_file_name']=file_name
    with open(request.session['now_project_repo_path']+file_name,'r') as f:
        data = f.read()
    return render(request, 'code_file.html', {'data': data,'title': file_name})
    #mycat_id = kwargs['pk']

def process_edit(request, *args, **kwargs):
    #print args
    #file_name = (kwargs['file_name'])
    print '处理代码修改'
    data = request.POST.get('data')
    commit_message = request.POST.get('commit_message')
    file_name = request.session['now_file_name']
    with open(request.session['now_project_repo_path']+file_name,'w') as f:
        f.write(data)
    GitFileController.change_commit(request.session['now_project_repo_path'],file_name,commit_message,request.session['user_name'],request.session['user_email'])

    description = '在项目'+request.session['now_project_name']+'中的'+request.session['head_branch']+'分支进行了注释为 "'+commit_message+'" 的提交'
    
    user_commit.record(request.session['user_name'], description)

    return HttpResponseRedirect(reverse('hub:code_file'))

def code_new(request):
    print '代码新建界面'
    return render(request,'code_new.html')


def process_new(request, *args, **kwargs):
    #print args
    #file_name = (kwargs['file_name'])
    print '处理代码新建'
    data = request.POST.get('data')
    commit_message = request.POST.get('commit_message')
    file_name = request.POST.get('title')
    request.session['now_file_name']=file_name
    with open(request.session['now_project_repo_path']+file_name,'w') as f:
        f.write(data)
    GitFileController.change_commit(request.session['now_project_repo_path'],file_name,commit_message,request.session['user_name'],request.session['user_email'])

    description = '在项目'+request.session['now_project_name']+'中的'+request.session['head_branch']+'分支进行了注释为 "'+commit_message+'" 的提交'
    
    user_commit.record(request.session['user_name'], description)

    return HttpResponseRedirect(reverse('hub:code_file'))


def commit(request):
    print '进入提交记录界面'

    c_list = GitFileController.log(request.session['now_project_repo_path'])
    #return render(request, 'commit.html', {'c_mes': c_mes,'c_name':c_name,'c_time':c_time,'c_len':c_len})
    return render(request, 'commit.html', {'c_list': c_list})

def branch(request):
    print '进入分支界面'

    if request.method == "POST":
        if request.POST.get('new_branch') != None:          #新建分支
            name = request.POST.get('new_branch')
            GitFileController.new_branch(request.session['now_project_repo_path'], name)
            status = 0

            msg = '在项目'+request.session['now_project_name']+'中新建了分支 '+name
            user_commit.record(request.session['user_name'], msg)

            result = "Create new branch success!"
            print(result)
        elif request.POST.get('branch_name') != None:            #删除分支
            print request.POST.get('branch_name')
            name = request.POST.get('branch_name')
            GitFileController.delete_branch(request.session['now_project_repo_path'], name)

            msg = '在项目'+request.session['now_project_name']+'中删除了分支 '+name
            user_commit.record(request.session['user_name'], msg)

            result = "Delete new branch sdsffsdf!"
            print(result)
        elif request.POST.get('frombranch') != None:        #合并分支
            msg = request.POST.get('message')
            frombranch = request.POST.get('frombranch')
            print msg
            frombranch_exist = GitFileController.merge(request.session['now_project_repo_path'],frombranch,msg)
        elif request.POST.get('tobranch') != None:          #切换分支
            tobranch = request.POST.get('tobranch')
            print tobranch
            GitFileController.switch_branch(request.session['now_project_repo_path'], tobranch)
            request.session['head_branch']=tobranch
    elif request.GET.get('branch_name') != None:            #删除分支
        print request.GET.get('branch_name')
        name = request.GET.get('branch_name')
        GitFileController.delete_branch(request.session['now_project_repo_path'], name)

        msg = '在项目'+request.session['now_project_name']+'中删除了分支 '+name
        user_commit.record(request.session['user_name'], msg)

        result = "Delete new branch success!"
        print(result)
    print 'done'
    data = GitFileController.show_branches_refs(request.session['now_project_repo_path'])
    print data
    return render(request, 'branch.html', {'data': data})



def login(request):
    print '进入登录界面'
    if request.method == 'POST':
        return process_LoginOrRegister(request)
    request.session['user_name']=None
    return render(request,'login.html')


def register(request):
    print '进入注册界面'
    if request.method == 'POST':
        return process_LoginOrRegister(request)
    return render(request,'register.html')

def profile(request):
    print ("进入主页")
    name = request.session['now_project_owner']
    if name == request.session['user_name']:
        is_user = True
    else : is_user = False

    pro_list = []

    pro_id_list = project_user.objects.filter(user_name=request.session['user_name'])
    for i, j in enumerate(pro_id_list):
        pro_list.append(Project.objects.get(pk=j.project_id))
    print (pro_list)
    print (request.session['user_name'])
    return render(request, 'projectCatalog.html', {'projects': pro_list,'is_user':is_user})

def process_LoginOrRegister(request):
    print ("登录/注册中")
    name = request.POST.get('name')

    email = request.POST.get('email',"noemail")

    password = request.POST.get('password')

    rePassword = request.POST.get('rePassword','norepassword')

    if email != "noemail":
        user_object = models.User.objects.create(user_name=name,email=email,password=password)
        GitFileController.create_dir(codehub_path+name)
    else:
        ff = models.User.objects.filter(user_name=name)
        #user_object = ff[0]
        if len(ff)!=0:user_object = ff[0]
        if len(ff)==0 or user_object.password!= password:
            print ("wrong password")
            list = ["密码或用户名错误"]
            print json.dumps(list)
            return render(request,'login.html',{'List':json.dumps(list)})
            #return HttpResponseRedirect(reverse('hub:login'),{'List':json.dumps(list)})

    request.session['user_email'] = user_object.email
    request.session['user_name'] = name
    request.session['now_project_owner'] = name

    return HttpResponseRedirect(reverse('hub:profile'))



def project_create(request):
    print '创建项目'

codehub2/hub/templates/code.html
<!DOCTYPE html>
<html>
   <!--head>
      <title>Bootstrap 模板</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      
	  
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

 
      
   </head-->
   <head>
   <meta charset="utf-8">
   <title>CodeHub</title>
   <link href="../static/Img/ele.jpg" rel="shortcut icon">
   <link href="/static/bootstrap.min.css" rel="stylesheet" />
</head>
   <body>

    {% include "_codeHead.html" %}
	 
 <div class="panel panel-default" style="background-color:GhostWhite">
  <div class="panel-body">
		<div class="panel panel-info">
  <div class="panel-heading" style="background-color:white">

	<br>
  <p style="font-family:arial;color:black;font-size:20px;"> <a href="{% url 'CodeHub:profile' %}">{{request.session.now_project_owner}}</a> / <a href="{% url 'CodeHub:code' %}">{{request.session.now_project_name}}</a></p>
<hr>项目描述
  </div>
  <div class="panel-body">
    <ul class="nav nav-tabs">
      <li role="presentation" class="active"><a href="{% url 'CodeHub:code' %}">代码</a></li>
      <li role="presentation"><a href="{% url 'CodeHub:commit' %}">提交记录</a></li>
      <li role="presentation"><a href="{% url 'CodeHub:branch' %}">分支</a></li>
      <li role="presentation"><a href="{% url 'CodeHub:member' %}">项目成员</a></li>
      {%if request.session.is_leader %}
          <li role="presentation"><a href="{% url 'CodeHub:settings' %}">设置</a></li>
      {% endif %}
    </ul>
<br>



<div class="btn-group" style="float:left">
                        <button type="button" id="switch" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{request.session.head_branch}}&nbsp;&nbsp;<span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu">
                            {% for branch in data %}
                            <li><a href="#">{{ branch }}</a></li>
                            {%endfor%}
                        </ul>
                    </div>
<div class="btn-group" role="group" aria-label="..." style="float:right">
  <button type="button" class="btn btn-default"><a href="code_new.html">新建</a></button>
  <button type="button" class="btn btn-default"><a href="upload.html">上传</a></button>
 <!--  <form action="/polls/upload/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="fafafa" />
    <input type="submit" value="上传" />
</form> -->
  <!-- <button type="button" id="cloneOrDownload" class="btn btn-default"><a href="download.html">Clone或下载</a></button> -->
  <div class="dropdown" style="float:left">
      <button type="button" class="btn btn-default dropdown-toggle btn-info"  id="cloneOrDownload" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            下载
          <span class="caret"></span>
    </button>
      <ul class="dropdown-menu" aria-labelledby="cloneOrDownload">
        <li><a id="downloadZip" href="#">下载zip</a></li>
        {% comment %} <li><a href="#">dev-2</a></li>
        <li><a href="#">dev-3</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">Separated link</a></li> {% endcomment %}
      </ul>
</div>
</div>
<br>
<br>
<br>
<table class="table">
  {% for file in files %}
          <tr>
          {% comment %} <td><a href="code_file?file_name={{file}}">{{file}}</a></td> {% endcomment %}
          {% if file == ".git" %}
          <td>{{file}}</td>
          {% else %}
             <td><a href="code_file?file_name={{file}}">{{file}}</a></td>
        
          {% endif %}

          {% comment %} <td style="text-align:right">时间（待完成）</td>
          <td >修改者（待完成）</td>
          <td >注释（待完成）</td> {% endcomment %}
          </tr>
  {% endfor %}
</table>

  </div>
  
  

</div>
 
 </div>
</div>
 
 
   <script src="/static/jquery.min.js"></script>
   <script src="/static/bootstrap.min.js"></script>


   <script>
     $('.dropdown-toggle').dropdown()
      $('.dropdown-menu a').on('click', function(){
       $(this).parent().parent().prev().html($(this).html() + '&nbsp;&nbsp;<span class="caret"></span>');
       if($(this).parent().parent().prev().attr("id")==="switch"){
            var to = ($("#switch").html()).split("&nbsp;&nbsp;");
            to_branch = to[0];
            $.post("{% url 'CodeHub:branch' %}",{'tobranch':to_branch});
       }
      })
   </script>

<script>
    $(document).ready(function(){
      $("#cloneOrDownload").click(function(){
        console.log("111111111")
        //console.log(ret)
        $.get("{% url 'CodeHub:getZip' %}",{}, function(ret){
            console.log(ret)
            $('#downloadZip').attr("href","/static/"+ret)
        })

      });
    });
</script>

   

   <script>
     /*
     * Project: Twitter Bootstrap Hover Dropdown
     * Author: Cameron Spear
     * Contributors: Mattia Larentis
     *
     * Dependencies?: Twitter Bootstrap's Dropdown plugin
     *
     * A simple plugin to enable twitter bootstrap dropdowns to active on hover and provide a nice user experience.
     *
     * No license, do what you want. I'd love credit or a shoutout, though.
     *
     * http://cameronspear.com/blog/twitter-bootstrap-dropdown-on-hover-plugin/
     */
    ;(function($, window, undefined) {
        // outside the scope of the jQuery plugin to
        // keep track of all dropdowns
        var $allDropdowns = $();

        // if instantlyCloseOthers is true, then it will instantly
        // shut other nav items when a new one is hovered over
        $.fn.dropdownHover = function(options) {

            // the element we really care about
            // is the dropdown-toggle's parent
            $allDropdowns = $allDropdowns.add(this.parent());

            return this.each(function() {
                var $this = $(this).parent(),
                    defaults = {
                        delay: 500,
                        instantlyCloseOthers: true
                    },
                    data = {
                        delay: $(this).data('delay'),
                        instantlyCloseOthers: $(this).data('close-others')
                    },
                    options = $.extend(true, {}, defaults, options, data),
                    timeout;

                $this.hover(function() {
                    if(options.instantlyCloseOthers === true)
                        $allDropdowns.removeClass('open');

                    window.clearTimeout(timeout);
                    $(this).addClass('open');
                }, function() {
                    timeout = window.setTimeout(function() {
                        $this.removeClass('open');
                    }, options.delay);
                });
            });
        };
        $('[data-hover="dropdown"]').dropdownHover();
    })(jQuery, this);
   </script>

   </body>
</html>

codehub2/hub/templates/code_edit.html
<!DOCTYPE html>
<html>
   <!--head>
      <title>Bootstrap 模板</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      
	  
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

 
      
   </head-->
   <head>
   <meta charset="utf-8">
   <title>CodeHub</title>
   <link href="../static/Img/ele.jpg" rel="shortcut icon">
   <link href="/static/bootstrap.min.css" rel="stylesheet" />
</head>
   <body>
   
   
    {% include "_codeHead.html" %}
	  
   
 <div class="panel panel-default" style="background-color:GhostWhite">
  <div class="panel-body">
		<div class="panel panel-info">
  <div class="panel-heading" style="background-color:white">

	<br>
   <p style="font-family:arial;color:black;font-size:20px;"> <a href="{% url 'CodeHub:profile' %}">{{request.session.now_project_owner}}</a> / <a href="{% url 'CodeHub:code' %}">{{request.session.now_project_name}}</a></p>
<hr>项目描述
  </div>
  <div class="panel-body">
    <ul class="nav nav-tabs">
      <li role="presentation" class="active"><a href="{% url 'CodeHub:code' %}">代码</a></li>
      <li role="presentation"><a href="{% url 'CodeHub:commit' %}">提交记录</a></li>
      <li role="presentation"><a href="{% url 'CodeHub:branch' %}">分支</a></li>
      <li role="presentation"><a href="{% url 'CodeHub:member' %}">项目成员</a></li>
      {%if request.session.is_leader %}
          <li role="presentation"><a href="{% url 'CodeHub:settings' %}">设置</a></li>
      {% endif %}
    </ul>
<br>



<div class="dropdown" style="float:left">
		  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
						Master
					<span class="caret"></span>
		</button>
			<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				<li><a href="#">dev-1</a></li>
				<li><a href="#">dev-2</a></li>
				<li><a href="#">dev-3</a></li>
				<li role="separator" class="divider"></li>
				<li><a href="#">Separated link</a></li>
			</ul>
</div>
<p style="float:left">&nbsp;&nbsp;</p>

<p style="font-family:arial;color:black;font-size:20px;float:left"> <a href="#">{{request.session.now_project_name}}</a>&nbsp;&nbsp;/&nbsp;&nbsp;{{title}}</p>

<br>
<br>
<br>

<form action="{% url 'CodeHub:process_edit' %}" method="post" >
<textarea name="data" class="form-control" rows="40">{{data}}</textarea>
<br>
<p style="font-family:arial;color:black;font-size:18px;"> 提交说明：</p>
<textarea name="commit_message" class="form-control" placeholder="输入提交说明..." rows="5"></textarea>
	<br>
  <button type="button" class="btn btn-default" style="float:right"><a href="code.html">取消</a></button>
  <p style="float:right">&nbsp;&nbsp;&nbsp;</p>
  <button type="submit" class="btn btn-default" style="float:right">提交</button>
</form>
  </div>
  
  

</div>
 
 </div>
</div>
 
 
   <script src="/static/jquery.min.js"></script>
   <script src="/static/bootstrap.min.js"></script>

   </body>
</html>

codehub2/hub/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hello codehub</h1>
</body>
</html>

codehub2/hub/templates/member.html
<!DOCTYPE html>
<html>
   <!--head>
      <title>Bootstrap 模板</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      
	  
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

 
      
   </head-->
   <head>
   <meta charset="utf-8">
   <title>CodeHub</title>
   <link href="../static/Img/ele.jpg" rel="shortcut icon">
   <link href="/static/bootstrap.min.css" rel="stylesheet" />
   <!--link href="http://cdn.bootcss.com/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet" /-->
</head>
   <body>
   

	    {% include "_codeHead.html" %}
      
 <div class="panel panel-default" style="background-color:GhostWhite">
  <div class="panel-body">
		<div class="panel panel-info">
  <div class="panel-heading" style="background-color:white">

	<br>
  <p style="font-family:arial;color:black;font-size:20px;"> <a href="{% url 'CodeHub:profile' %}">{{request.session.now_project_owner}}</a> / <a href="{% url 'CodeHub:code' %}">{{request.session.now_project_name}}</a></p>
<hr>项目描述
  </div>
  <div class="panel-body">
    <ul class="nav nav-tabs">
      <li role="presentation"><a href="{% url 'CodeHub:code' %}">代码</a></li>
      <li role="presentation"><a href="{% url 'CodeHub:commit' %}">提交记录</a></li>
      <li role="presentation"><a href="{% url 'CodeHub:branch' %}">分支</a></li>
      <li role="presentation" class="active"><a href="{% url 'CodeHub:member' %}">项目成员</a></li>
      {%if request.session.is_leader %}
          <li role="presentation"><a href="{% url 'CodeHub:settings' %}">设置</a></li>
      {% endif %}
    </ul>
<br>


<form action="{% url "CodeHub:proMem" %}" method="post" class="form-inline" style="float:right">
    {% csrf_token %}
  <div class="form-group">
    <input type="text" name="i_name" class="form-control" placeholder="输入新成员的用户名...">
  </div>
  <button type="submit" class="btn btn-default">添加成员</button>
</form>
<br>
<br>
<br>

<table class="table">
	{% for menber in members %}
        <tr>
	    <td>{{ menber.user_name }}</td>
	    <td ><a href="{% url "CodeHub:delMem" %}?member_name={{ menber.user_name }}">
            <button type="submit" class="btn btn-default" method='get' style="float:right" >删除</button></a>
        </td>
	<!--td>11-13 13:13</td>
	<td ></td>
	<td ><button type="button" style="float:right" class="btn btn-default">下载</button></td-->
	    </tr>
    {% endfor %}

</table>

  </div>
  
  

</div>
 
 </div>
</div>
 
 
   <script src="/static/jquery.min.js"></script>
   <script src="/static/bootstrap.min.js"></script>

   </body>
</html>

codehub2/hub/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="upload.html/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="fafafa" />
    <input type="submit" value="上传" />
    <a href="{% url 'CodeHub:code' %}">返回</a>
</form>
</body>
</html>